services:
  # ── Django API ────────────────────────────────────────────────────────────
  - type: web
    name: playto-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER_EXTERNAL_HOSTNAME
        fromService:
          name: playto-api
          type: web
          property: host
      - key: CORS_ALLOWED_ORIGINS
        value: https://playto-frontend.onrender.com
      - key: POSTGRES_DB
        fromDatabase:
          name: playto-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: playto-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: playto-db
          property: password
      - key: POSTGRES_HOST
        fromDatabase:
          name: playto-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: playto-db
          property: port
      - key: CELERY_BROKER_URL
        fromService:
          name: playto-redis
          type: keyvalue
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          name: playto-redis
          type: keyvalue
          property: connectionString
      - key: CRON_SECRET
        generateValue: true



  # ── Vite Frontend (Static Site) ───────────────────────────────────────────
  - type: web
    name: playto-frontend
    runtime: static
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://playto-api.onrender.com/api/v1

  # ── Redis (Key Value) ────────────────────────────────────────────────────
  - type: keyvalue
    name: playto-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

databases:
  - name: playto-db
    databaseName: playto
    user: playto
    plan: free
