# Generated by Django 5.2.13 on 2026-04-25 13:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paise', models.PositiveBigIntegerField()),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('attempt_count', models.IntegerField(default=0)),
                ('failure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.bankaccount')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'state'], name='payout_merchant_state_idx'), models.Index(fields=['state', 'updated_at'], name='payout_state_updated_idx')],
            },
        ),
    ]
