# Generated by Django 5.2.13 on 2026-04-25 13:48

import django.db.models.deletion
import idempotency.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('in_flight', 'In flight'), ('done', 'Done')], default='in_flight', max_length=20)),
                ('request_params', models.JSONField()),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=idempotency.models.default_expires_at)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='merchants.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expires_at'], name='idempotency_expires_idx')],
                'constraints': [models.UniqueConstraint(fields=('merchant', 'key'), name='unique_idempotency_key_per_merchant')],
            },
        ),
    ]
